language: java
jdk:
  - openjdk6

after_failure:
  - "cat bootstrap-core/target/surefire-reports/de.agilecoders.wicket.core.markup.html.bootstrap.button.dropdown.DropDownButtonTest.txt"
  - "cat bootstrap-core/target/surefire-reports/TEST-de.agilecoders.wicket.core.markup.html.bootstrap.button.dropdown.DnTest.xml"

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
